### ISSUE TITLE
Inserttag for active tag

### ISSUE THREAD

**Issue by denniserdmann** [numero2/contao-tags#12]
When you are on the filtered news/events list, it would be great to use the selected tag (or multiple tags) inside a headline via inserttags.

The result could look like this:

`<h1>Articles for [TAG 1]</h1>`

**Comment by michb** [comment]
We've added an inserttag for this. Could you check if this helps you and give some feedback. 
For usage and examples please refer the readme.

**Comment by denniserdmann** [comment]
I have to re-open this issue. Inserttag is working, but it ends tags that i don't used, see https://github.com/numero2/contao-tags/blob/master/src/EventListener/TagsListener.php#L75-L76

Output is **Articles for Tag 1, dlas, dddlas**

**Comment by michb** [comment]
We just fix that, not sure how this happend. 
But why is there also an empty tag after "Tag 1"? 
Is it work corretly now or is there some problem in parsing the tags?

**Comment by denniserdmann** [comment]
my fault, there was no double comma. 

I will add another issue for a problem i stumbled.
