### ISSUE TITLE
Tags for events_full results in error

### ISSUE THREAD

**Issue by denniserdmann** [numero2/contao-tags#13]
`Warning: foreach() argument must be of type array|object, string given` for this line 

```
<?php foreach( $this->tags as $tag ): ?>
```

According to the readme, it should be possible to use the same lines for event_full, too.

BTW: Event-List Modul ist working

**Comment by bennyborn** [comment]
Hmm. It seems like the `getAllEvents`-Hook isn't used for the `EventReader` module - at least in Contao 4.13 🤔

**Comment by bennyborn** [comment]
So Contao provides no Hooks for the `ModuleEventReader` at all. In order to display the tags in `event_full` you need to add the following code:

```php
<?php

use Contao\ModuleEventReader;
use Contao\ModuleModel;
use Contao\System;

$moduleModel = ModuleModel::findOneById(19);
$module = new ModuleEventReader($moduleModel);

$tagListener = System::getContainer()->get('numero2_tags.listener.events');
$event = $tagListener->parseEvent($this->arrData, $module);

$this->tags = $event['tags'];
$this->tagsRaw = $event['tagsRaw'];

?>
```

Unfortunately we have no reference to the current reader module so you'll need to adjust the ID of the module in line 7 yourself.
