### ISSUE TITLE
Improvement > Tags selected AND/OR

### ISSUE THREAD

**Issue by biowebfr** [numero2/contao-tags#14]
Hi,
first, I have to say your extension is really great ! Thank you for that.

I use it on latest contao 5.3.11.

I've come to use the Tag Filter in News list. But It lacks something that could make this feature even more "powerfull".

When I tag filter like this :

Tag1, Tag2

The result list all news with Tag1, Tag2 and Tag1+Tag2

I want to tag filter my news using something like this :

"tag1, tag2"

So the result should list exclusively news with Tag1+Tag2.

Do you think it's possible to add this option in the tagfilter module ?

Thank you for your time and your work ;)

Renaud

**Comment by bennyborn** [comment]
I'm not sure but doesn't the option `All tags must match` in the newslist module do exactly this?

**Comment by biowebfr** [comment]
Oh! You're right. 

In fact this option is present the Newslist module. And this is the one which I didn't notice and it's working as expected. 

Thank you! :)

But I also saw this option in the News Tag Cloud module :
![image](https://github.com/user-attachments/assets/10f1579d-31e7-43ad-9292-3bafa1b5dffb)

Do you know what it's for?

**Comment by bennyborn** [comment]
This would filter the tags shown in the Tag Cloud depending on the "News tags" you pre-selected.

For example you checked "Tag2" and enabled `All tags must match` your Tag Cloud will only show this tag and tags from all other news articles that have at least "Tag2" set.

It's a bit complicated to describe but I'll guess you'll understand what it does if you got some more tags and news for testing 😊

**Comment by biowebfr** [comment]
I think I get it and this is a good feature ;).

I used to have https://github.com/hschottm/tags on Contao 3.5, I was very dispointed to see that it was not available for Contao 5 but yours seems to be very inspired from this one :).

So I checked the "All tags must match" in the Mod Tag Cloud but when I select the Tag3 that has only one match, others are still showing :

![image](https://github.com/user-attachments/assets/98f8a9cb-cdcc-451e-bf28-0553f9080270)
![image](https://github.com/user-attachments/assets/b8ec36cd-bb3d-4c9e-972b-0e68f2ca0fe2)

As you can see Tag3 is only used once :

![image](https://github.com/user-attachments/assets/91ca6dd2-54ee-4c14-a369-18edbddd3162)

Am I finnaly don't get it that much? :p

Thanks a lot.

**Comment by michb** [comment]
The tag cloud modules can be filter by tags in the backend. As you can select multiple tags in the module configuration, e.g. under `News tags`, you can configure if `all tags must match`, speaking and / or  comparision.
But the tag cloud modules to not react to a selection in the frontend.

In your example the tag cloud will show all used tags in the select news archive.

**Comment by biowebfr** [comment]
Ok this one is tricky.

I try, please believe me but I can't understand what it means to do.

Here is 3 tests 

Test 1 :
![image](https://github.com/user-attachments/assets/e6a230db-629a-45a9-97f5-56cdadcb8fa7)
Result :
![image](https://github.com/user-attachments/assets/e1d8de91-cd1b-4180-b4b5-e180cfea02db)
Select a tag :
![image](https://github.com/user-attachments/assets/ea16eb22-6b74-41e0-bb73-99a162c2ddf2)

Test 2 :
![image](https://github.com/user-attachments/assets/9a09ac3a-3a21-4f8f-8c76-e47090fd1729)
Result :
![image](https://github.com/user-attachments/assets/6ddba522-91b3-4522-ba9e-333dca6d4fd3)
Select a tag :
![image](https://github.com/user-attachments/assets/262684e4-0d18-49b1-ba5a-c0ce0d684eb7)


Test 3 : 
![image](https://github.com/user-attachments/assets/9ac3a0d1-23ef-4f48-8334-3296ef6cb8cb)
Result :
![image](https://github.com/user-attachments/assets/0539667e-95ab-432b-894d-cb8ae94e2a84)

I'm really sorry, but I don't get the logic behind these Tag Cloud module options.

Are those tests resultas ok for you?

**Comment by bennyborn** [comment]
Please keep in mind that the settings of the `Tag Cloud` module does not affect the listing of the `Newslist` module.

Lets go through your tests...

**Test 1:** You checked `Ceci est le tag 1` so the Cloud makes sure to alwas show the tags of all articles having this tag

**Test 2:** You checked `Ceci est le tag 1` and `Tag2` as well as `All tags must match` so the Cloud shows the tags of matching articles **IF** there are news articles having **BOTH** of these tags

Test 3: You checked all 3 tags as well as `All tags must match`. Since there is no article having all three of these tags no tags will be listed at all
