### ISSUE TITLE
Compatibility witch Contao News Categories extension

### ISSUE THREAD

**Issue by biowebfr** [numero2/contao-tags#15]
Hi!

I tried to use this extension with this one https://github.com/codefog/contao-news_categories/ but when I filter tags it doesn't keep the categorie url I'm focused on.

/actualites/categorie/categorie-1 is replaced by /actualites/tag/WyJDZWNpIGVzdCBsZSB0YWcgMSJd

![image](https://github.com/user-attachments/assets/687fe6e6-9517-4e86-92ec-b7c0ffd580ef)

I imagine something like this : /actualites/categorie/categorie-1/tag/WyJDZWNpIGVzdCBsZSB0YWcgMSJd

So do you think those two excellent extensions could be compatible or is it just a dream that will never comme true ? :)

Thank you for your time.

**Comment by bennyborn** [comment]
Unfortunately this won't be possible due to the nature of how Contao's `newsListFetchItems` and `newsListCountItems` Hooks work. These Hooks do not build on each other but each Hook has its own result. So whatever extension comes last will dictate which news entries will be shown.

**Comment by biowebfr** [comment]
Ok, thank you for your explanations. :)
I'll make some choice then :)
