### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by hinzke** [numero2/contao-tags#2]
Is it possible to display a counter with the number of stored tags in the tag list?

**Comment by bennyborn** [comment]
It certainly is. Could you test if [5cde89f](https://github.com/numero2/contao-tags/commit/5cde89f635b79ffa68e5cbfa6f00508e817d460f) works like intended?

**Comment by hinzke** [comment]
Perfekt! It works!

**Comment by bennyborn** [comment]
Great. Just released version 0.0.4 😉🎉
