### ISSUE TITLE
Darstellung von News mit bestimmten Tags

### ISSUE THREAD

**Issue by cc-ben** [numero2/contao-tags#4]
Hi zusammen,
im Rahmen eines kleineren Projektes für einen Verein stehe ich grade vor dem Problem, dass auf einer Seite entsprechende News mit einem festgelegten Tag stehen sollen.
 z.B. sollen auf der Seite "Schützenzug XYZ" alle News mit dem Tag "schuetzenxyz" ausgegeben werden.

Die erste Idee, war mit der "Nachrichtenliste mit ähnlichen Tags" hier ranzugehen, die Ausgabe ist aber grundsätzlich leer.

Die nächste Idee war, mit dem Custom Elements Modul von Rocksolid Ein Element zu generieren, welches über die vorhandenen Tags geht und entsprechende News ausspuckt. Klappt aber auch nicht. 

Habt ihr hier eine Idee oder einen Denkanstoß, wie man das umsetzen könnte?

Im Einsatz ist Contao 5.1.x 

Viele Grüße
Ben

**Comment by bennyborn** [comment]
Hi Ben, ein solches Feature haben wir tatsächlich schon beabsichtig zu integrieren, sind aber leider bisher nicht dazu gekommen.

Das "Nachrichtenliste mit ähnlichen Tags" nicht funktioniert ist klar, das ist nur für die Detailseite ausgelegt weil es sich eben anhand des Alias der aktuellen News die passenden Tags zusammensucht.

Gerne könntest Du dieses Modul duplizieren und um eine Auswahl der Tags im Backend erweitern - im Prinzip ist das ja nichts anderes wie eine vorgefilterte Newsliste.

Sobald wir Zeit für das Feature haben gebe ich hier nochmal bescheid.

**Comment by bennyborn** [comment]
@cc-ben an das Issue hat irgendwie keiner mehr gedacht aber das Feature ist bereits implementiert. Es gibt ein Nachrichtenlisten-Modul welches nach bestimmten Tags vorselektiert werden kann.
